---
- name: AWSCli dependencies
  package:
    name: ["python3", "unzip"]
    state: present

- name: Create URL for ARM64
  set_fact:
    url_download: "{{ AWSCLI_URL }}-aarch64.zip"
  when: ansible_architecture == 'arm64'

- name: Create URL for x86_64
  set_fact:
    url_download: "{{ AWSCLI_URL }}-x86_64.zip"
  when: ansible_architecture == 'x86_64'

- name: Debug
  debug:
    msg: "{{ url_download }}"

- name: awscli download
  get_url:
    url: "{{ url_download }}"
    dest: /tmp/awscliv2.zip
    mode: 0600

- name: awscli unarchive
  unarchive:
    remote_src: yes
    src: /tmp/awscliv2.zip
    dest: /tmp

- name: awscli install
  command: /tmp/aws/install --bin-dir {{ BINARY_DIR }} --install-dir {{ INSTALL_DIR }} --update
  changed_when: false
