---
haproxy_version: 1.9
haproxy_daemon_state: started
haproxy_daemon_enabled: yes
haproxy_chroot: /var/lib/haproxy
haproxy_max_connections: 10000
haproxy_socket: /var/run/haproxy.stats
haproxy_multithreaded: false
haproxy_nb_proc: '__HA_PROXY_NB_PROC__'
haproxy_nb_thread: '__HA_PROXY_NB_THREAD__'
haproxy_cpu_map: '__HA_PROXY_CPU_MAP__'
haproxy_user: haproxy
haproxy_group: haproxy

# unique ID
haproxy_unique_id: true
haproxy_unique_id_header: X-HAPROXY-UID
haproxy_unique_id_format: '%{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid'

# custom log format
haproxy_logs_enabled: true
haproxy_custom_log_format: '[%t]\ %ac/%fc/%bc/%bq/%sc/%sq/%rc\ %Tq/%Tw/%Tc/%Tr/%Tt\ %tsc\ %ci:%cp\ %fi:%fp\ %si:%sp\ %ft\ %sslc\ %sslv\ %{+Q}r\ %ST\ %b:%s\ "%CC"\ "%hr"\ "%CS"\ "%hs"\ req_size=%U\ resp_size=%B\ %ID'
haproxy_custom_log: true

# access stats
haproxy_stats_enabled: true
haproxy_stats_address: '__HAPROXY_STATS_ADDRESS__'
haproxy_stats_port: '__HAPROXY_STATS_PORT__'
haproxy_stats_user: '__HAPROXY_STATS_USER__'
haproxy_stats_pwd: '__HAPROXY_STATS_PWD__'

haproxy_global_vars:
haproxy_resolvers: []
haproxy_frontends: []
haproxy_backends: []
