- hosts: bastion
  become: true
  remote_user: "{{ ansible_user | default('debian') }}"
  roles:
    - ansible-packages
    - ansible-awscli
    - ansible-teleport
    # - secure-ssh
    # - attach-eip
    # - dehydrated
  vars:
    service_name: "{{ SERVICE }}"
