packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.1"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {

  // sources = ["source.amazon-ebs.autogenerated_1", "source.qemu.autogenerated_2", "source.virtualbox-ovf.autogenerated_3"]
  sources = ["source.amazon-ebs.ubuntu"]

  provisioner "shell" {
    inline = ["sleep 20"]
    only   = ["amazon-ebs"]
  }

  provisioner "shell" {
    scripts = ["${path.root}/../../scripts/bootstrap.sh"]
  }

  provisioner "ansible-local" {
    extra_arguments  = ["--extra-vars \"SERVICE=${var.service}\"", "-e ansible_python_interpreter=/usr/bin/python3"]
    group_vars       = "${path.root}/../../../ansible/playbooks/group_vars"
    inventory_groups = ["${var.inventory_groups}"]
    playbook_dir     = "${path.root}/../../../ansible"
    playbook_file    = "${var.playbook_file}"
  }

  provisioner "shell" {
    scripts = ["${path.root}/../../scripts/cleanup.sh"]
  }

}