
source "qemu" "autogenerated_1" {
  boot_wait         = "1800s"
  disk_interface    = "virtio"
  disk_size         = 6000
  format            = "qcow2"
  headless          = true
  http_directory    = "httpdir"
  http_port_max     = 10089
  http_port_min     = 10082
  iso_checksum_type = "sha256"
  iso_checksum_url  = "http://cdimage.ubuntu.com/releases/18.04.1/release/SHA256SUMS"
  iso_url           = "http://cdimage.ubuntu.com/releases/18.04.1/release/ubuntu-18.04.1-server-amd64.iso"
  net_device        = "virtio-net"
  output_directory  = "output_ubuntu"
  qemuargs          = [["-m", "4096M"]]
  shutdown_command  = "sudo shutdown -P now"
  ssh_host_port_max = 2229
  ssh_host_port_min = 2222
  ssh_password      = "password"
  ssh_port          = 22
  ssh_username      = "ubuntu"
  ssh_wait_timeout  = "1000000s"
  vm_name           = "ubuntu18.qcow2"
}

build {
  sources = ["source.qemu.autogenerated_1"]

}
