# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source

source "amazon-ebs" "debian" {
  ami_description = "debian-${var.service}-${var.role}"
  ami_name        = "${var.service}-${var.role}-${legacy_isotime("2006-01-02T15-04-05")}"
  ami_regions     = ["eu-west-1"]
  // ami_users                   = "${var.shared_account}"
  associate_public_ip_address = true
  instance_type               = var.instance_type
  region                      = var.region
  profile                     = var.profile
  skip_create_ami             = var.skip_create_ami
  source_ami                  = var.source_ami

  run_tags = {
    Appli = var.PROJECT_NAME
    Env   = var.PROJECT_ENV
    Name  = "Packer Builder ${var.service}"
    ci    = var.PROJECT_CI
    git   = var.PROJECT_GIT
    owner = var.PROJECT_OWNER
  }

  security_group_id = var.security_group_id
  ssh_pty           = true
  ssh_username      = "admin"
  subnet_id         = var.subnet_id
  vpc_id            = var.vpc_id

  tags = {
    Appli     = var.PROJECT_NAME
    Env       = var.PROJECT_ENV
    Name      = "${var.service}-${var.role}"
    Role      = var.role
    Service   = var.service
    SourceAMI = var.source_ami
    ci        = var.PROJECT_CI
    git       = var.PROJECT_GIT
    owner     = var.PROJECT_OWNER
  }
}

source "qemu" "ubuntu" {
    boot_command      = [
    "<enter><wait><f6><wait><esc><wait>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>",
    "<bs><bs><bs>",
    "/install/vmlinuz noapic ",
    "file=/floppy/preseed.cfg ",
    "debian-installer=en_US auto locale=en_US kbd-chooser/method=us ",
    "hostname=vagrant ",
    "fb=false debconf/frontend=noninteractive ",
    "keyboard-configuration/modelcode=SKIP ",
    "keyboard-configuration/layout=USA ",
    "keyboard-configuration/variant=USA console-setup/ask_detect=false ",
    "passwd/user-fullname=vagrant ",
    "passwd/user-password=vagrant ",
    "passwd/user-password-again=vagrant ",
    "passwd/username=vagrant ",
    "initrd=/install/initrd.gz -- <enter>"
  ]
  floppy_files      = ["../../_tools/packer/templates/debian-buster/http/preseed.cfg"]
  boot_wait         = "1800s"
  disk_interface    = "virtio"
  disk_size         = 6000
  format            = "qcow2"
  headless          = true
  // http_directory    = "httpdir"
  // http_port_max     = 10089
  // http_port_min     = 10082
  iso_urls           = [
    "http://cdimage.ubuntu.com/releases/18.04.5/release/ubuntu-18.04.5-server-amd64.iso"
  ]
  iso_checksum = "8c5fc24894394035402f66f3824beb7234b757dd2b5531379cb310cedfdf0996"
  //net_device        = "virtio-net"
  output_directory  = "output-ubuntu1804"
  qemuargs          = [["-m", "4096M"]]
  shutdown_command  = "echo packer | sudo shutdown -P now"
  ssh_password      = "password"
  ssh_port          = 22
  ssh_username      = "ubuntu"
  ssh_wait_timeout  = "10000s"
  vm_name           = "ubuntu1804"
  use_default_display = true
}

// source "virtualbox-ovf" "autogenerated_3" {
//   checksum             = "${var.box_checksum}"
//   communicator         = "ssh"
//   guest_additions_mode = "disable"
//   headless             = true
//   output_directory     = "/tmp/packer_output"
//   shutdown_command     = "sudo shutdown -P now"
//   skip_export          = true
//   source_path          = "${var.box_folder}/box.ovf"
//   ssh_port             = "62222"
//   ssh_private_key_file = "~/.vagrant.d/insecure_private_key"
//   ssh_pty              = true
//   ssh_skip_nat_mapping = true
//   ssh_username         = "vagrant"
//   ssh_wait_timeout     = "1000s"
//   target_path          = "/tmp/packer_cache"
//   vboxmanage           = [["modifyvm", "{{ .Name }}", "--cpus", "2"], ["modifyvm", "{{ .Name }}", "--memory", "2048"], ["modifyvm", "{{ .Name }}", "--nic1", "nat"], ["modifyvm", "{{ .Name }}", "--natpf1", "packerssh,tcp,127.0.0.1,62222,,22"], ["modifyvm", "{{ .Name }}", "--uart1", "0x3F8", "4"], ["modifyvm", "{{ .Name }}", "--macaddress1", "${var.box_base_mac}"], ["modifyvm", "{{ .Name }}", "--accelerate3d", "off"], ["modifyvm", "{{ .Name }}", "--graphicscontroller", "vmsvga"], ["modifyvm", "{{ .Name }}", "--pae", "off"], ["modifyvm", "{{ .Name }}", "--nestedpaging", "on"], ["modifyvm", "{{ .Name }}", "--vram", "128"]]
// }