# datadog-agent
datadog_additional_groups:
  - adm
datadog_config:
  api_key: '__DATADOG_API_KEY__'
  tags:
    - "environment:__DATADOG_TAG_ENV__"
    - "role:bastion"
  log_level: INFO
  logs_enabled: "true"
  logs_config:
    use_http: "true"
    use_compression: "true"
  process_config:
    enabled: "true"
    strip_proc_arguments: "false"
  apm_config:
    enabled: "false"
datadog_checks:
  tcp_check:
    init_config:
    instances:
      - name: sshd
        search_string: ['sshd']
        host: localhost
        port: 22
        collect_response_time: true
    logs:
      - type: file
        path: /var/log/auth.log
        service: sshd
        source: bastion
        log_processing_rules:
          - name: exclude_rule_localhost
            pattern: \W+127\.0\.0\.1
            type: exclude_at_match
          - name: exclude_rule_cron
            pattern: \W+CRON
            type: exclude_at_match