---
varnish_sysvinit_config_path: /etc/default
varnish_systemd_config_path: /lib/systemd/system

varnish_package_name: "varnish"
varnish_version: "6.2"

varnish_vmod_dynamic_enabled: true
varnish_vmod_dynamic_tests: false

varnish_use_default_vcl: true
varnish_default_vcl_template_path: default.vcl.j2

varnish_default_content_backend_host: "__VARNISH_DEFAULT_BACKEND__"
varnish_default_content_backend_port: "__VARNISH_DEFAULT_BACKEND_PORT__"

varnish_listen_port: "80"
varnish_secret: "14bac2e6-1e34-4770-8078-974373b76c90"
varnish_config_path: '/etc/varnish'
varnish_gomplates_path: '/etc/varnish/gomplates'
varnish_limit_nofile: 131072

varnish_admin_listen_host: "127.0.0.1"
varnish_admin_listen_port: "6082"

varnish_storage: "file,/var/lib/varnish/varnish_storage.bin,256M"
varnish_pidfile: /run/varnishd.pid

varnishd_extra_options: ""

varnish_cluster:
  varnish-01:
    host: "__VARNISH_NODE_01_FQDN__"
    port: "80"
  varnish-02:
    host: "__VARNISH_NODE_02_FQDN__"
    port: "80"

# Setting this value to false will have the effect to replicate cache on all varnish nodes
varnish_sharding: true

varnish_enabled_services:
  - varnish

varnish_services_state: stopped
varnish_services_enabled: no

varnish_apt_repo: deb https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main

varnish_vmod_dynamic_repo: https://github.com/nigoroll/libvmod-dynamic.git

# Optionally define additional backends.
# varnish_backends:
#   apache:
#     host: 10.0.2.2
#     port: 80
#   nodejs:
#     host: 10.0.2.3
#     port: 80

# Optionally define vhosts pointed at different backends.
# varnish_vhosts:
#   example.com:
#     backend: apache
#   nodejs.example.com:
#     backend: nodejs

# Optionally define varnish excluded domains
# varnish_domain_excludes:
#    - www.example.com
