---
- name: debian | add backports apt repository
  apt_repository:
    repo: deb http://httpredir.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: backports

- name: debian | add haproxy apt-key
  apt_key:
    url: https://haproxy.debian.net/bernat.debian.org.gpg
    state: present

- name: debian  | add haproxy dedicated apt repository
  apt_repository:
    repo: deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-{{ haproxy_version }} main
    state: present
    filename: haproxy

- name: debian | outil TRNG
  apt:
    name: ['haproxy','rng-tools']
    state: present
    update_cache: yes
    default_release: '{{ ansible_distribution_release }}-backports'
