---
- include: Debian.yml
  when: ansible_distribution == "Debian"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_vars: Debian.yml
  when: ansible_distribution == "Debian"

- include_vars: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: haproxy disable service
  service: 
    name: haproxy
    state: '{{ haproxy_daemon_state }}'
    enabled: '{{ haproxy_daemon_enabled }}'

- name: haproxy main config
  template:
    src: '00-haproxy.cfg.j2'
    dest: '/etc/haproxy/00-haproxy.cfg'
    mode: 0640

- name: remove default main config
  file: 
    path: '/etc/haproxy/haproxy.cfg'
    state: absent

- name: haproxy defaults config
  template:
    src: '01-defaults.cfg.j2'
    dest: '/etc/haproxy/01-defaults.cfg'
    mode: 0640

- name: haproxy resolvers config
  template:
    src: '02-resolvers.cfg.j2'
    dest: '/etc/haproxy/02-resolvers.cfg'
    mode: 0640
  with_items:
    - '{{ haproxy_resolvers }}'

- name: haproxy userlists
  template:
    src: '03-userlists.cfg.j2'
    dest: '/etc/haproxy/03-userlists.cfg'
    mode: 0640
  with_items:
    - '{{ haproxy_userlists }}'
    
- name: haproxy frontend configs
  template:
    src: '10-frontend.cfg.j2'
    dest: '/etc/haproxy/10-{{ item.name }}-frontend.cfg'
    mode: 0640
  with_items:
    - '{{ haproxy_frontends }}'

- name: haproxy backend configs
  template:
    src: '20-backend.cfg.j2'
    dest: '/etc/haproxy/20-{{ item.name }}-backend.cfg'
    mode: 0640
  with_items:
    - '{{ haproxy_backends }}'

- name: haproxy stats config
  template:
    src: '30-stats.cfg.j2'
    dest: '/etc/haproxy/30-stats.cfg'
    mode: 0640
  when: haproxy_stats_enabled

- name: install haproxy-multiconf script
  copy:
    src: 'haproxy-multiconf'
    dest: '/usr/local/bin/'
    mode: 0755

- name: install haproxy-multiconf service unit file
  copy:
    src: 'haproxy-multiconf.service'
    dest: '/etc/systemd/system/'
    mode: 0644

- name: install haproxy service unit file
  copy:
    src: 'haproxy.service'
    dest: '/etc/systemd/system/'
    mode: 0644

- include: logging.yml
  when: haproxy_logs_enabled | bool

#- name: haproxy scripts
#  template:
#    src: script.{{ item }}.sh.j2
#    dest: /usr/local/bin/haproxy-{{ item }}
#    mode: 755
#  with_items:
#    - s3-certs
#
#- name: TCP syn flood attacks Protection
#  lineinfile:
#    dest: /etc/sysctl.conf
#    line: '{{ item }}'
#  with_items:
#    - net.ipv4.tcp_syncookies = 1
#    - net.ipv4.conf.all.rp_filter = 1x
#    - net.ipv4.tcp_max_syn_backlog = 1024

# Recommendations sysctl values for haproxy
# https://wiki.evolix.org/HowtoHaproxy
# Augmentation du nombre de connexions simultanées possibles
#  net.netfilter.nf_conntrack_max=1000000
#  # Réduction du délai de timeout FIN
#  net.ipv4.tcp_fin_timeout=20
#  # Elargissement de la plage de ports locaux utilisables
#  net.ipv4.ip_local_port_range=1025 65534
#  # augmentation du nombre maximum d'orphelins
#  net.ipv4.tcp_max_orphans=65536
