---
- name: ubuntu | add repository from PPA and install its signing key
  apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
    mode: 0644

- name: ubuntu | outil TRNG
  apt:
    name: ['haproxy','rng-tools']
    state: present
    update_cache: yes

  # Avoid SSL Handshake errors on ubuntu by upgrading rng-tools and restarting it
  # https://discourse.haproxy.org/t/ssl-handshake-failure/1252/2
- name: haproxy rng-config
  lineinfile:
    dest: /etc/default/rng-tools
    line: 'HRNGDEVICE=/dev/urandom'
    insertafter: EOF
  notify: restart rng-tools