---
- name: Add Teleport apt key.
  ansible.builtin.apt_key:
    url: https://deb.releases.teleport.dev/teleport-pubkey.asc
    state: present

- name: Add Teleport repository.
  ansible.builtin.apt_repository:
    repo: deb https://deb.releases.teleport.dev/ stable main
    state: present

- name: Update apt cache.
  ansible.builtin.apt: update_cache=yes

- name: Ensure Teleport is installed in Debian.
  ansible.builtin.apt:
    name: "{{ teleport_packages }}"
    state: "{{ teleport_packages_state }}"
