---
- name: restart rng-tools
  service: name=rng-tools enabled=yes state=restarted

- name: enable haproxy
  service: name=haproxy enabled=yes

- name: restart rsyslog
  service: name=rsyslog state=restarted
  when: ansible_connection != 'local'
