---
all:
  vars:
    ansible_become: true
    ansible_user: 'vagrant'
    k3s_use_docker: true
    k3s_no_traefik: true
    k3s_write_kubeconfig_mode: '644'
    k3s_become_for_all: true
    apt_specific_packages:
       - python-jmespath
       - python3-pip
k3s_nodes:
  hosts:
    k3s:
      ansible_connection: 'local'
      k3s_flannel_interface: enp0s8
      k3s_control_node: true
