name: Ansible Linte

# on: [
#   push,
#   pull_request]

on:
  push:
    branches:
    - main
    paths:
    - '_tools/ansible/**'
  pull_request:
    branches:
    - main

# environment:
#   GITHUB_WORKSPACE:

jobs:

  test:
    name: Molecule aws-cli role
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule docker yamllint ansible ansible-lint 'molecule[docker]'

      - name: Run Molecule tests for aws-cli role
        run: molecule test
        working-directory: _tools/ansible/roles/aws-cli
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
