name: Terraform Baseline

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - 'baseline/**'
    - '_tools/terraform/modules/**'
  pull_request:
    branches:
    - '*'
    paths:
    - '.github/**'
    - 'baseline/**'
    - '_tools/terraform/modules/**'

jobs:

  terraform-baseline:
    name: 'Terraform Baseline'
    runs-on: ubuntu-latest
    env:
      environment: qa
    steps:
      - name: Setup terraform provider
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: baseline-qa-eu-west-1
        shell: bash
        run: |
          make init
          make validate
          make version
          make plan
        working-directory: ./baseline/${{ env.environment }}/eu-west-1
