name: Terraform MyApp

on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - 'myapp/**'
    - '_tools/terraform/modules/**'
  pull_request:
    branches:
    - '*'
    paths:
    - '.github/**'
    - 'myapp/**'
    - '_tools/terraform/modules/**'

jobs:

  terraform-myapp:
    name: 'TF MyApp QA'
    runs-on: ubuntu-latest
    env:
      environment: qa
      region: eu-west-1
    steps:
      - name: Setup terraform provider
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: myapp-${{ env.environment }}-${{ env.region }}
        shell: bash
        run: |
          make init
          make validate
          make version
          make plan
        working-directory: ./myapp/${{ env.environment }}/${{ env.region }}
