# name: Terraform Baseline

# on:
#   push:
#     branches:
#     - main
#     paths:
#     - '.github/**'
#     - 'baseline/**'
#     - '_tools/terraform/modules/**'
#   pull_request:
#     branches:
#     - '*'
#     paths:
#     - '.github/**'
#     - 'baseline/**'
#     - '_tools/terraform/modules/**'

# jobs:

#   terraform-baseline:
#     name: 'TF Baseline QA'
#     runs-on: ubuntu-latest
#     env:
#       environment: qa
#       region: eu-west-1
#     steps:
#       - name: Setup go-task
#         uses: pnorton5432/setup-task@v1
#         with:
#           task-version: 3.43.3
#       - name: Setup terraform provider
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.11.4
#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
#       - name: Checkout Source
#         uses: actions/checkout@v4

#       - name: baseline-${{ env.environment }}-${{ env.region }}
#         shell: bash
#         run: |
#           task tf:init
#           task tf:validate
#           task tf:plan
#         working-directory: ./baseline/${{ env.environment }}/${{ env.region }}
